emscripten-forge/recipes

.github/workflows/build_minimal.yaml
.github/workflows/build_py.yaml
.github/workflows/ci_env.yml

* not depend on conda-build at all

trying monkeypatching

---

.github/workflows/build_py.yaml
browser_test_package.py
build_and_test.sh
build_packages.sh

with browser test

---

.github/workflows/build_changed_recipes.yaml
builder.py
recipes/recipes_emscripten/regex/recipe.yaml
testing/browser_test_package.py
testing/node_test_package.py

- use `empack` to pack each build pkg on its own
- upload `*.js / *.data` as artifact to GitHub

create emscripten packed pkgs

---

.github/workflows/build_changed_recipes.yaml
builder.py

build all workflow

---

.github/workflows/build_recipes.yaml
builder.py

* auto delete build envs in cleanup

auto delete build envs in cleanup

---

recipes/recipes_emscripten/pandas/recipe.yaml

The latest release is `1.4.3`: https://github.com/pandas-dev/pandas/releases/tag/v1.4.3

Update to the latest `pandas` release

---

recipes/recipes_emscripten/eigen/build.sh
recipes/recipes_emscripten/eigen/recipe.yaml

Package added following the docs in https://blog.jupyter.org/mamba-meets-jupyterlite-88ef49ac4dc8 .

Add eigen recipe

---

empack_config.yaml

This fixes issues with multiple packages: bqplot, ipyleaflet, ipympl

empack_config: prevent filtering .json files

---

recipes/recipes_emscripten/expat/build.sh
recipes/recipes_emscripten/expat/recipe.yaml
recipes/recipes_emscripten/udunits2/0001-static-path-xml.patch
recipes/recipes_emscripten/udunits2/build.sh
recipes/recipes_emscripten/udunits2/recipe.yaml

@ocefpaf was interested in this :)

Udunits and expat

---

empack_config.yaml

This is the final step to have Folium working:

Fix Folium package data

---

empack_config.yaml

Fixes https://github.com/jupyterlite/jupyterlite/issues/760.

Include xarray's static files (HTML and CSS)

---

recipes/recipes_emscripten/sympy/recipe.yaml

Bump `sympy` to its latest release.

Bump `sympy` to `1.11`

---

recipes/recipes_emscripten/pyjs/recipe.yaml

pyjs 0.14.0 -> 0.15.0

---

recipes/recipes/emscripten_emscripten-32/recipe.yaml

fixed missing bumped buildversion in emscripten_emscripten-32 pkg

fixed missing bumped buildversion in emscripten_emscripten-32

---

recipes/recipes/emscripten_emscripten-32/recipe.yaml

There was a missing bump in https://github.com/emscripten-forge/recipes/pull/212

Bump emscripten-32

---

recipes/recipes_emscripten/pyjs/recipe.yaml

update pyjs from 0.15.0 to 0.16.0

update pyjs from 0.15.0 to 0.16.0

---

recipes/recipes_emscripten/picomamba/recipe.yaml

update picomamba to 0.3.0

---

recipes/recipes_emscripten/picomamba/recipe.yaml

picomamba 0.4.0

---

recipes/recipes_emscripten/xeus-lua/build.sh
recipes/recipes_emscripten/xeus-lua/recipe.yaml

@DerThorsten not sure if we have to add any run dependency since everything is statically linked.

Added recipes for xeus-lua

---

recipes/recipes_emscripten/arrow-python/recipe.yaml

This should just be a test dependency

python-arrow: Remove hypothesis dependency

---

.github/workflows/build_all.yaml
.github/workflows/build_simple.yaml

* added workflow which always builds one package
* This is needed since we otherwise only build packages with changes and if we do not change any package but add changes that break the build system we do not notice it

added workflow to always build at aleast a simple package

---

.github/workflows/build_all.yaml
.github/workflows/build_recipes.yaml
.github/workflows/build_simple.yaml

* added workflow_dispatch trigger
* removed superfluous steps from main ci

changed workflow

---

recipes/recipes_emscripten/python/build.sh
recipes/recipes_emscripten/python/patch_sysconfigdata.py
recipes/recipes_emscripten/python/recipe.yaml
recipes/recipes_emscripten/regex/recipe.yaml

* update the python sys-config data in a more robust way

update python sysconfig v2

---

README.md

Follow-up to https://github.com/emscripten-forge/recipes/pull/298.

Remove the `ipywidgets` example from the README

---

README.md

This appears to be a typo in the README

Update platform target triple in README

---

recipes/recipes_emscripten/python_abi/recipe.yaml

Needed for https://github.com/emscripten-forge/recipes/pull/303

Update `python_abi` to 3.11

---

recipes/recipes_emscripten/pyjs/recipe.yaml

update pyjs to 0.19.0

---

recipes/recipes_emscripten/requests-wasm-polyfill/recipe.yaml

update wasm request polyfill

---

bump_recipes_versions.py

Follow-up #316 
This should help at least find the recipe files now.
cc @martinRenou if you'll want to test the workflow afterwards

Fix glob in version update script

---

bump_recipes_versions.py

bump_recipes script: fix sha check for Numpy

---

.github/workflows/build_recipes.yaml

missing activate

---

.github/workflows/new_versions_v2.yaml
bump_recipes_versions_and_create_pr.py

this creates a single PR for each recipe where a new version is available

per recipe pr

---

recipes/recipes_emscripten/xeus-python/recipe.yaml

Update Xeus Python to the latest version: https://github.com/jupyter-xeus/xeus-python/releases/tag/0.15.9

Update Xeus Python

---

recipes/recipes_emscripten/protobuf/recipe.yaml

This should fix https://github.com/emscripten-forge/recipes/issues/184

Add `protobuf`

---

bump_recipes_versions.py

For now, just adding labels and reading them.
We should later use this labels reading for checking if automerge should happen.

Tweaking bot automerge feature

---

recipes/recipes_emscripten/llvm/build.sh
recipes/recipes_emscripten/llvm/recipe.yaml

Add the LLVM base project. Other projects that live under the same source tree are not included.

Add LLVM base project

---

.github/workflows/build_recipes.yaml

enable update again

---

README.md

local-build-instructions

---

recipes/recipes_emscripten/xeus-lite/recipe.yaml

trigger rebuild of xeus-lite

---

recipes/recipes_emscripten/bzip2/recipe.yaml
recipes/recipes_emscripten/lua/recipe.yaml
recipes/recipes_emscripten/nlohmann_json/recipe.yaml
recipes/recipes_emscripten/pybind11/recipe.yaml
recipes/recipes_emscripten/pybind11_json/recipe.yaml
recipes/recipes_emscripten/sqlite/recipe.yaml
recipes/recipes_emscripten/xcanvas/recipe.yaml
recipes/recipes_emscripten/xeus-lite/recipe.yaml
recipes/recipes_emscripten/xproperty/recipe.yaml
recipes/recipes_emscripten/xwidgets/recipe.yaml

Bump build numbers for recipes changed in #772 but not including #785

Bump build numbers

---

recipes/recipes_emscripten/pysocks/recipe.yaml
recipes/recipes_emscripten/pysocks/test_pysocks.py

Pysocks recipe

---

recipes/recipes_emscripten/xeus-python/recipe.yaml

use new pyjs in xeus-python

---

recipes/recipes_emscripten/xeus-python/recipe.yaml

update xeus-python to use pyjs 1.6.0

update xeus-python to use pyjs 1.6.0

---

recipes/recipes_emscripten/xeus-javascript/recipe.yaml

xeus-javascript 0.3.0

---

recipes/recipes_emscripten/xeus-python/recipe.yaml

add pyjs to run dependencies

---

recipes/recipes_emscripten/xeus-javascript/recipe.yaml

bump xeus-javascript

---

conda_build_config.yaml
emci/constants.py
emci/rattler_build.py
rattler_conda_build_config.yaml
variant_config.yaml

pass explicit conda build config to rattler-build

pass explicit conda build config to rattler-build

---

recipes/recipes_emscripten/lfortran/recipe.yaml

1) Pinning lfortran version to be used out of conda-forge (https://github.com/emscripten-forge/recipes/pull/862#discussion_r1561238333)
2) Adding Ubaid as a maintainer (https://github.com/emscripten-forge/recipes/pull/872#issuecomment-2049988796)

Minor updates in lfortran recipe

---

.github/workflows/build_simple.yaml
emci/__main__.py
emci/constants.py
emci/rattler_build.py
recipes/recipes/emscripten_emscripten-wasm32/activate.sh
recipes/recipes/emscripten_emscripten-wasm32/rattler_recipe.yaml
recipes/recipes/emscripten_emscripten-wasm32/recipe.yaml
recipes/recipes_emscripten/highs/rattler_recipe.yaml

* better handling of `CMAKE_ARGS` in compiler activation script
* testing to build a non-python cmake package in CI
* giving boa priority as upload with rattler-build is not yet working

more rattler-build related changes

---

.github/run_with_pixi.yaml
.github/workflows/build_recipes.yaml
.github/workflows/build_simple.yaml
.github/workflows/run_with_pixi.yaml
README.md
emci/__main__.py
emsdk/setup_emsdk.sh
pixi.toml
recipes/recipes/cross-python_emscripten-wasm32/rattler_recipe.yaml
recipes/recipes/cross-python_emscripten-wasm32/recipe.yaml
recipes/recipes/emscripten_emscripten-wasm32/rattler_recipe.yaml
recipes/recipes/emscripten_emscripten-wasm32/recipe.yaml
recipes/recipes/pytester/rattler_recipe.yaml
recipes/recipes_emscripten/ipython/rattler_recipe.yaml
recipes/recipes_emscripten/ipython/recipe.yaml

set everything up with pixi.
```bash
pixi run setup                                          
pixi run build-emscripten-wasm32-pkg recipes/recipes_emscripten/regex 
```

setup with pixi

---

.gitignore

This will speed up the git (and also vscode I think).

add .pixi/ and output/ to gitignore

---

docs/adding_packages.md
docs/blog/.authors.yml
docs/blog/posts/pixi.md
docs/blog/posts/rattler_build.md
docs/blog/posts/rust.md
mkdocs.yml
pixi.toml

added a mini blog with news about the emscripten-forge project

added blog

---

recipes/recipes_emscripten/ncurses/build.sh
recipes/recipes_emscripten/ncurses/rattler_recipe.yaml
recipes/recipes_emscripten/ncurses/recipe.yaml

Add ncurses

---

recipes/recipes_emscripten/xz/build.sh
recipes/recipes_emscripten/xz/recipe.yaml

cc @IsabelParedes / @DerThorsten

add xz recipe

---

recipes/recipes_emscripten/bitarray/build.sh
recipes/recipes_emscripten/bitarray/recipe.yaml
recipes/recipes_emscripten/bitarray/run_test.py
recipes/recipes_emscripten/bitarray/test_bitarray.py

The tests for the bitarray still do not run. I tried to write one that runs using pytest, however i get a runtime error.

Add bitarray recipe

---

recipes/recipes_emscripten/pydantic_core/recipe.yaml

It seems the bot never tried to update this recipe, probably due to the wrong URL

Pydantic-core update

---

emci/bot/bump_recipes_versions.py

disable_bot_merging

---

pixi.toml

adding_curl

---

ci_env.yml

remove_quetz_client_use_curl

---

recipes/recipes/pytester/recipe.yaml
recipes/recipes_emscripten/pyjs/recipe.yaml

fix comparison in `build` section

---

recipes/recipes_emscripten/lfortran/recipe.yaml

Update lfortran to 0.38.0

---

ci_env.yml

add requests

---

recipes/recipes_emscripten/orjson/build.sh
recipes/recipes_emscripten/orjson/recipe.yaml
recipes/recipes_emscripten/orjson/test_orjson.py

Fixes https://github.com/emscripten-forge/recipes/issues/1193
Recipe based on the `pycrdt` one.

Add `orjson`

---

emci/bot/bump_recipes_versions.py

currently the bot only labels recipes as 'automerge' if there are `test_*.py` files.
This PR changes the logic to read the recipe yaml and look for the "tests" section.

improve bot

---

recipes/recipes_emscripten/libevalhyd/recipe.yaml

Attempting to add libevalhyd based on xtensor

Add libevalhyd

---

recipes/recipes_emscripten/cockle_fs/build.sh
recipes/recipes_emscripten/cockle_fs/recipe.yaml
recipes/recipes_emscripten/coreutils/build.sh
recipes/recipes_emscripten/coreutils/recipe.yaml
recipes/recipes_emscripten/grep/build.sh
recipes/recipes_emscripten/grep/recipe.yaml

adde node env

---

.github/workflows/build_docs.yaml
.github/workflows/on_compiler_changes.yaml
.github/workflows/run_with_pixi.yaml
conda_build_config.yaml

**note** this PR wants to merge in the branch `emscripten-3.1.58` and **not** main.
This branch (and PRs against this branch) will be used to build & upload packages for emscripten-3.1.58

emscripten-3.1.58

---

recipes/recipes_emscripten/python/recipe.yaml

trigger python build with new emscripten version

trigger python build with new emscripten version

---

emci/bot/bump_recipes_versions.py

ping the maintainers when a  PR to update the versions fails or has no test

ping maintainers on failing PRs

---

recipes/recipes_emscripten/r-htmltools/recipe.yaml

Add r-htmltools

---

recipes/recipes_emscripten/r-nlme/build.sh
recipes/recipes_emscripten/r-nlme/recipe.yaml

Should be rebased on top of #1317

Add r-nlme

---

recipes/recipes_emscripten/r-mgcv/recipe.yaml

Add r-mgcv

---

recipes/recipes_emscripten/r-vctrs/recipe.yaml

Add r-vctrs

---

recipes/recipes_emscripten/r-tibble/recipe.yaml

Depends on #1324 , #1346 , #1341 , #1303 , #1342

Add r-tibble

---

recipes/recipes_emscripten/llvm/patches/skip_undefined_symbols_at_link_step.patch
recipes/recipes_emscripten/llvm/recipe.yaml

Fix wasm-ld flags for creating correct shared wasm binaries

---

.github/workflows/new_versions.yaml
emci/bot/bump_recipes_versions.py
emci/git_utils.py

* run ci for main and emscripten-3.1.73
* make PRs against that branch

version update bot changes st. it works for multiple branches

---

recipes/recipes/emscripten_emscripten-wasm32/build_compiler_package.sh
recipes/recipes/emscripten_emscripten-wasm32/recipe.yaml

also create symlinks for 3.1.45 version

python file symlinks in compiler [3.1.45]

---

recipes/recipes_emscripten/cockle_fs/build.sh
recipes/recipes_emscripten/cockle_fs/recipe.yaml

Update `cockle_fs` to emscripten 3.1.73.

Update cockle_fs to emscripten 3.1.73

---

recipes/recipes_emscripten/swiglpk/build.sh
recipes/recipes_emscripten/swiglpk/recipe.yaml

swig-glpk test flags

---

recipes/recipes_emscripten/ncurses/build.sh
recipes/recipes_emscripten/ncurses/recipe.yaml

Update `ncurses` to emsdk 3.1.73

Update ncurses to emsdk 3.1.73

---

recipes/recipes_emscripten/liblzma/build.sh
recipes/recipes_emscripten/liblzma/recipe.yaml
recipes/recipes_emscripten/libpython/recipe.yaml
recipes/recipes_emscripten/numpy/recipe.yaml
recipes/recipes_emscripten/pyjs/build.sh
recipes/recipes_emscripten/pyjs/recipe.yaml
recipes/recipes_emscripten/python/Setup.local
recipes/recipes_emscripten/python/recipe.yaml

* lzma recipe
* python with lzma support
* pyjs with lzma support

python lzma

---

pixi.toml

The file was previously renamed in this commit https://github.com/emscripten-forge/recipes/commit/381f8527ac1e2f7ca4f02c5c0f1a8f6d438564b8

Rename conda_build_config.yaml to variant.yaml

---

conda_build_config.yaml

Sparrow build required cmake >=3.28 
https://github.com/emscripten-forge/recipes/actions/runs/13106802877/job/36562908051?pr=1847

Update cmake version in conda_build_config

---

recipes/recipes_emscripten/nelson/patches/0001-Diff-enableTrivial-is-non-const.patch
recipes/recipes_emscripten/nelson/recipe.yaml

Update `nelson` to emscripten 3.1.73.

Update nelson to emscripten 3.1.73

---

recipes/recipes_emscripten/pixman/build.sh
recipes/recipes_emscripten/pixman/emscripten.meson.cross
recipes/recipes_emscripten/pixman/patches/0001-disable-threads.patch
recipes/recipes_emscripten/pixman/recipe.yaml

Build pixman without threat support

---

recipes/recipes_emscripten/r-base/build.sh
recipes/recipes_emscripten/r-base/config.site
recipes/recipes_emscripten/r-base/patches/0014-Set-cairo-as-default-bitmap-type.patch
recipes/recipes_emscripten/r-base/pre.js
recipes/recipes_emscripten/r-base/recipe.yaml

Add r-base

---

recipes/recipes_emscripten/r-bit64/GPL-2
recipes/recipes_emscripten/r-bit64/recipe.yaml

Add r-bit64

---

recipes/recipes_emscripten/r-colorspace/recipe.yaml

Add r-colorspace

---

recipes/recipes_emscripten/r-data.table/recipe.yaml

Add r-data.table

---

recipes/recipes_emscripten/r-digest/recipe.yaml

Add r-digest

---

recipes/recipes_emscripten/r-fansi/patches/0001-Ignore-custom-limit-checks.patch
recipes/recipes_emscripten/r-fansi/recipe.yaml

Add r-fansi

---

recipes/recipes_emscripten/r-farver/recipe.yaml

Add r-farver

---

recipes/recipes_emscripten/r-fastmap/recipe.yaml

Add r-fastmap

---

recipes/recipes_emscripten/r-glue/recipe.yaml

Add r-glue

---

recipes/recipes_emscripten/r-jsonlite/recipe.yaml

Add r-jsonlite

---

recipes/recipes_emscripten/r-lattice/recipe.yaml

Add r-lattice

---

recipes/recipes_emscripten/r-magrittr/recipe.yaml

Add r-magrittr

---

recipes/recipes_emscripten/r-mass/recipe.yaml

Add r-mass

---

recipes/recipes_emscripten/r-mime/GPL-2
recipes/recipes_emscripten/r-mime/recipe.yaml

Add r-mime

---

recipes/recipes_emscripten/r-rcpp/GPL-2
recipes/recipes_emscripten/r-rcpp/patches/0001-Disable-demangler.patch
recipes/recipes_emscripten/r-rcpp/recipe.yaml

Add r-rcpp

---

recipes/recipes_emscripten/r-rlang/recipe.yaml

Add r-rlang

---

recipes/recipes_emscripten/r-stringi/build.sh
recipes/recipes_emscripten/r-stringi/recipe.yaml

Add r-stringi

---

recipes/recipes_emscripten/r-utf8/recipe.yaml

Add r-utf8

---

recipes/recipes_emscripten/r-xfun/recipe.yaml

Add r-xfun

---

recipes/recipes_emscripten/r-yaml/recipe.yaml

Add r-yaml

---

recipes/recipes_emscripten/r-cachem/recipe.yaml

Add r-cachem

---

recipes/recipes_emscripten/r-hexbin/GPL-2
recipes/recipes_emscripten/r-hexbin/recipe.yaml

Add r-hexbin

---

recipes/recipes_emscripten/r-vroom/recipe.yaml

Add r-vroom

---

recipes/recipes_emscripten/r-readr/recipe.yaml

Add r-readr

---

recipes/recipes_emscripten/r-dplyr/recipe.yaml

Add r-dplyr

---

recipes/recipes_emscripten/r-purrr/recipe.yaml

Add r-purrr

---

recipes/recipes_emscripten/r-tidyr/recipe.yaml

Add r-tidyr

---

recipes/recipes_emscripten/r-later/patches/0001-Do-not-link-with-atomic-lib.patch
recipes/recipes_emscripten/r-later/recipe.yaml

Add r-later

---

recipes/recipes_emscripten/r-promises/recipe.yaml

Add r-promises

---

recipes/recipes_emscripten/r-matrix/recipe.yaml

Add r-matrix

---

recipes/recipes_emscripten/r-haven/recipe.yaml

Add r-haven

---

recipes/recipes_emscripten/r-ggrepel/recipe.yaml

Add r-ggrepel

---

recipes/recipes_emscripten/xeus-r/build.sh
recipes/recipes_emscripten/xeus-r/recipe.yaml

Add xeus-r

---

recipes/recipes_emscripten/scipy/recipe.yaml

rebuild with libopenblas linking against libf2c

rebuild_with_fixed_blas

---

recipes/recipes_emscripten/osqp/build.sh
recipes/recipes_emscripten/osqp/recipe.yaml

Added recipe for [OSQP](https://osqp.org).

Added osqp 1.0.0

---

pixi.toml
recipes/recipes/emscripten_emscripten-wasm32/recipe.yaml

Missing on a clean install (e.g. Pixi docker image)

Add missing deps

---

pixi.toml
recipes/recipes/emscripten_emscripten-wasm32/recipe.yaml

Add basic dependencies needed in bare docker image.

Add missing dependencies

---

recipes/recipes_emscripten/xeus/recipe.yaml

Update xeus from 5.2.0 to 5.2.1

Update xeus from 5.2.0 to 5.2.1

---

.github/workflows/build_recipes.yaml

* removed config file which was only needed when building with the already removed conda-build / boa
* eliminating dead code from important CI files

removed superflous files

---

recipes/recipes_emscripten/arrow-cpp/recipe.yaml

added tests to allow the bot  to merge PR on its own to reduce maintenance overhead

Added testing to arrow-cpp recipe st. automerging updates works

---

recipes/recipes_emscripten/llvm/build.sh

When we started out with building llvm, release & debug builds used to fail. I think we should be able to get it now though !

Attempt Release build for llvm 20.1.4

---

recipes/recipes_emscripten/xwidgets/recipe.yaml

Bumping xwidgets to use latest xeus and nlohmann_json

Bump xwidgets to use latest xeus

---

recipes/recipes_emscripten/xtensor-blas/build.sh
recipes/recipes_emscripten/xtensor-blas/patches/shared.patch
recipes/recipes_emscripten/xtensor-blas/recipe.yaml

To be put to use with xeus-cpp-lite

Add recipe for xtensor-blas

---

recipes/recipes_emscripten/git2cpp/build.sh
recipes/recipes_emscripten/git2cpp/emscripten.meson.cross
recipes/recipes_emscripten/git2cpp/recipe.yaml

Add new recipe for [git2cpp](https://github.com/QuantStack/git2cpp) which will be used in `cockle`.

Add recipe for git2cpp

---

recipes/recipes_emscripten/xwidgets/recipe.yaml

Added to ensure frontend widget rendering support

Add jupyterlab_widgets in the xwidgets recipe

---

emci/bot/bump_recipes_versions.py

R package recipes have multiple URLs because oftentimes one of them is not reachable. Previously, the bot was not updating any R packages (except `r-base`) with the error `url is not a template`. With this change, it will at least check the first `url` in the recipe for a new version.

Handle recipes with multiple urls [bot]

---

emci/bot/bump_recipes_versions.py

Recipes with only major and minor version numbers (no patch version) fail to be updated because the version is a `ScalarFloat` instead of a string.
```
Error in /.../recipes_emscripten/libdeflate: 
'ScalarFloat' object has no attribute 'split'
```

Ensure version is a string

---

emci/bot/bump_recipes_versions.py

[bot] Handle recipes with source paths

---

recipes/recipes_emscripten/git2cpp/recipe.yaml

Update git2cpp to version 0.0.2. Doing this manually to demonstrate workflow.

Update git2cpp to version 0.0.2

---

recipes/recipes_emscripten/aiohttp/recipe.yaml
recipes/recipes_emscripten/arrow-cpp/recipe.yaml
recipes/recipes_emscripten/biopython/recipe.yaml
recipes/recipes_emscripten/boost-histogram/recipe.yaml

Adds licence and license_file info (4 at a time)

Fix some missing licenses information

---

recipes/recipes_emscripten/git2cpp/build.sh
recipes/recipes_emscripten/git2cpp/recipe.yaml

Enable C++ exceptions in `git2cpp`.

Enable C++ exceptions in git2cpp

---

recipes/recipes_emscripten/pyclipper/recipe.yaml
recipes/recipes_emscripten/pyclipper/test_pyclipper.py

Add pyclipper

---

recipes/recipes_emscripten/fastcan/build.sh
recipes/recipes_emscripten/fastcan/emscripten.meson.cross
recipes/recipes_emscripten/fastcan/recipe.yaml
recipes/recipes_emscripten/fastcan/test_fastcan.py

fastcan: A fast canonical-correlation-based greedy search algorithm
homepage: https://fastcan.readthedocs.io/en/latest/
repository: https://github.com/scikit-learn-contrib/fastcan/
Language: Python, Cython, meson

Add fastcan
