emscripten-forge/recipes

recipes/widgetsnbextension/recipe.yaml

widgetsnbextension is not noarch, so we need this recipe for now. This can be removed when https://github.com/conda-forge/widgetsnbextension-feedstock/issues/52 is fixed

Add widgetsnbextension

---

package_platforms.json
recipes/ipywidgets/recipe.yaml

Cutting out the ipykernel dependency for now (it's not technically needed if running in e.g. xeus-python)

Add ipywidgets recipe

---

.github/workflows/build_changed_recipes.yaml

If it fails to upload, it should be because someone changed a recipe without changing the version number or build number, so it's good that it fails

Remove the force upload

---

.github/workflows/build_recipes.yaml
builder.py
ci_env.yml
recipes/recipes_emscripten/pyjs/recipe.yaml
recipes/recipes_emscripten/pytest_driver/build.sh
recipes/recipes_emscripten/pytest_driver/recipe.yaml
recipes/recipes_emscripten/pytest_driver_node/build.sh
recipes/recipes_emscripten/pytest_driver_node/recipe.yaml
recipes/recipes_emscripten/wasm_requests/build.sh
recipes/recipes_emscripten/wasm_requests/recipe.yaml
recipes/recipes_emscripten/wasm_requests/test_wasm_requests.py
testing/browser_test_package.py
testing/node_test_package.py
testing/pytest_driver/CMakeLists.txt
testing/pytest_driver/pytest_driver.cpp
testing/testpage/empty.html
testing/testpage/worker.js

* added  recipes:
* `pyjs`
* `wasm_requests`
* integrated  `pyjs` in `pytest_driver` / `pytest_driver_node` pkg
* use `wasm_requests` as first `pyjs` based package which is tested
* changed `playwright` test suite st. tests are run in a worker
* added `nodejs` to wasm deps

testdriver with `pyjs` support

---

.github/workflows/.condarc_post
.github/workflows/build_recipes.yaml
conda_build_config.yaml
recipes/recipes_emscripten/python/recipe.yaml

currently the python pks has run dependencies on pks which are actually linked as static libraries. In the recipe the depencies are correctly listed as run dependencies, but the build config was setup st. these pks where added as run dependencies

removed pkgs from config/pin_run_as_build

---

recipes/recipes_emscripten/pyjs/build.sh
recipes/recipes_emscripten/pyjs/recipe.yaml

REPL is not working with last build since it was not in Release mode (gives some error message about cannot call slice on undefined)

use explicit release bld for pyjs

---

empack_config.yaml

We're not actually gaining so much from ignoring those, but it can go up to one useless MB with many widgets libraries, so it's still worth doing it.

Ignore some patterns

---

recipes/recipes_emscripten/re2/patches/no-context.patch
recipes/recipes_emscripten/re2/recipe.yaml

This is an attempt to remove the `re2::hooks::context` (which is optional anyway if `thread_local` is not supported) to help with building `arrow-python` which depends on RE2. For some reason that extern object leads to linking issues so this is an attempt to remove it from the the whole problem.

RE2: removed context extern thread_local object

---

conda_build_config.yaml
recipes/recipes_emscripten/pydro/recipe.yaml

atm the pydro build fails with:
```
2023-03-07T10:57:20.6822707Z Setting environment variables:
2023-03-07T10:57:20.6826001Z PATH = /home/runner/.cache/empack/emsdk-3.1.27:/home/runner/.cache/empack/emsdk-3.1.27/upstream/emscripten:/home/runner/.cache/empack/emsdk-3.1.27/node/14.18.2_64bit/bin:/home/runner/micromamba-root/envs/ci-env/conda-bld/pydro-0_1678178275615/_build_env/bin:/home/runner/micromamba-root/envs/ci-env/conda-bld/pydro-0_1678178275615/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin:/home/runner/micromamba-root/envs/ci-env/condabin:/home/runner/micromamba-root/envs/ci-env/conda-bld/pydro-0_1678178275615/_build_env:/home/runner/micromamba …
```

changed numpy pinning

---

README.md

When I was porting a recipe to emscripten-forge, I didn't immediately realise that it was supposed to conform to the Boa recipe specification. I hope that something like this note will make it more obvious to oblivious developers such as myself going forward! :)

docs: add note about use of Boa

---

recipes/recipes_emscripten/python/build.sh
recipes/recipes_emscripten/python/recipe.yaml

* remove broken symlinks:
* prefix/bin contains a lot of broken links
* prefix/lib/pkgconfig contains **only** broken links 
* also remove python binary itself as this is:
1. completely useless
2. completely untested
3. the proper way is embed libpython / pyjs in the project where you need to embed python

remove bin and broken symlinks from python package

---

recipes/recipes_emscripten/python/build.sh
recipes/recipes_emscripten/python/recipe.yaml

keep python/bin and python executables as ohtherwise cross-python and other downstream tools break!

python pkg: add dummy file to prefix/bin

---

recipes/recipes_emscripten/ipywidgets/recipe.yaml

Looks like we need to revert https://github.com/emscripten-forge/recipes/pull/298 if we want to continue using more recent versions of `ipywidgets` for now.
Since `ipykernel` was added back in https://github.com/jupyter-widgets/ipywidgets/pull/3749.

Revert "Remove ipywidgets recipe (#298)"

---

recipes/recipes_emscripten/pyjs/recipe.yaml
testing/package_testing.py

add new pyjs version to the recipe but pin the old version of pyjs in testing since pyjs 1.0.0 is API breaking

new pyjs in recipe, but old one in testing

---

ci_env.yml

pinning pyjs_code_runner before we merge and release https://github.com/emscripten-forge/empack/pull/66.
Empack itself is already upper bounded with`< 3`

pinning pyjs_code_runner

---

.github/workflows/build_all.yaml
.github/workflows/build_recipes.yaml
.github/workflows/build_simple.yaml
ci_env.yml
testing/package_testing.py
testing/test_empack_config.py

* use new empack stack (ie empack >= 3.0.0,  pyjs-code-runner >= 2.0.0, pyjs >-= 1.0.0) 
* This disables the node tests as we dropped node support atm (this might change, because we just need to install a fetch-like package for node to make node work again)
* there should be no changes for the users/recipe authors, besides:
*  package might start to work since pyjs 1.0.0 uses a better way of instantiation the shared libraries  (ie in the correct order)
* The `PREFIX` in the tests is always `/` instead of some random temporary directory

use new empack stack

---

recipes/recipes/emscripten_emscripten-32/recipe.yaml

Otherwise envsubst isn't there on macOS

add gettext to build env for emscripten-emscripten-32

---

.github/workflows/build_recipes.yaml

create directories, otherwise ci will fail with
```
find ${CONDA_PREFIX}/conda-bld/emscripten-32/*.tar.bz2 -exec quetz-client https://beta.mamba.pm/channels/emscripten-forge {} \;
find: ‘/home/runner/micromamba-root/envs/ci-env/conda-bld/linux-64/*.tar.bz2’: No such file or directory
```

create directories, st find wont complain

---

recipes/recipes_emscripten/llvm/build.sh
recipes/recipes_emscripten/llvm/recipe.yaml

It seems like cross-compiling Clang and LLD separately from LLVM is tricky due to requiring native versions of some LLVM components as well as WASM versions. It is also wasteful in general. This is an attempt to include these within the llvm package. It should still produce separate static libraries.

Extend llvm package to include clang and lld

---

recipes/recipes_emscripten/argparse/build.sh
recipes/recipes_emscripten/argparse/recipe.yaml

This PR adds the 3.0 version of the argparse package (https://github.com/p-ranav/argparse). I've used cpp-argparse to keep the naming convention similar to that of conda-forge

Added cpp-argparse package

---

recipes/recipes_emscripten/xeus-javascript/recipe.yaml

- Update to the latest version: https://github.com/jupyter-xeus/xeus-javascript/releases/tag/0.2.0
- Update links as the repo is now under the `jupyter-xeus` organization: https://github.com/jupyter-xeus

Update to `xeus-javascript` 0.2.0

---

README.md
recipes/recipes_emscripten/contourpy/build.sh
recipes/recipes_emscripten/contourpy/recipe.yaml
recipes/recipes_emscripten/contourpy/test_contourpy.py
recipes/recipes_emscripten/matplotlib/recipe.yaml

The version of Matplotlib built in this repo, 3.8.2, requires ContourPy to calculate contours. As ContourPy is not yet in this repo any attempt to plot contours in Matplotlib fails with an import error.
Here I am adding ContourPy 1.0.7 which is the latest version available that does not use `meson` for building. I haven't yet succeeded with the `meson` build due to some problems cross-compiling, and I would like to have ContourPy available as soon as possible and I'll upgrade to the latest version in due course.
The build itself is quite simple with one compiler warning disabled which will not be necessary after the next `pybind11` release. The tests are similar to those for `pyodide`.
I have added `contourpy` as a runtime dependency of `matplotlib` and bumped the build number. Matplotlib …

Add new package contourpy 1.0.7

---

ci_env.yml

Fixes https://github.com/emscripten-forge/recipes/issues/811
`make` and `cmake` might not be installed globally on some system, so we can also install them from conda-forge.

Add missing dev dependencies

---

recipes/recipes_emscripten/cppinterop/build.sh
recipes/recipes_emscripten/cppinterop/patches/cppinterop/0003-cmake-config-fix-library-suffix-and-prefix.patch
recipes/recipes_emscripten/cppinterop/recipe.yaml

@vgvassilev Here is the patch to CppInterOp so it picks the right suffix when finding the library.
@anutosh491 @JohanMabille can you review this PR for me please?

Add 0003-cmake-config-fix-library-suffix-and-prefix.patch to CppInterOp

---

recipes/recipes_emscripten/cppinterop/patches/cppinterop/0005-Fix-config-for-msvc.patch
recipes/recipes_emscripten/cppinterop/patches/cppinterop/0006-Export-symbols-in-Windows-DLL.patch
recipes/recipes_emscripten/cppinterop/recipe.yaml

Adds 0005-Fix-config-for-msvc.patch & 0006-Export-symbols-in-Windows-DLL.patch patches cppinterop

Add 0005-Fix-config-for-msvc.patch & 0006-Export-symbols-in-Windows-DLL.patch patches cppinterop

---

recipes/recipes_emscripten/qutip/recipe.yaml
recipes/recipes_emscripten/qutip/test_qutip.py

This updates the qutip recipe to build qutip 5.0.1.
In addition to updating the version number and the package hash, it also updates the tests.

Update qutip to 5.0.1

---

recipes/recipes_emscripten/lfortran/recipe.yaml

`bison `: required by `build0.sh`. We have a tarball so this should not be needed
`re2c`: required by `build0.sh`. We have a tarball so this should not be needed
`python`: again should not be needed. Used by `build0.sh`
`toml`: we do not run tests for the wasm build, so should not be needed.
Also I think when we have the `LFortran_Build_to_wasm `as `ON`, we naturally have the `WITH_XEUS `option as `OFF`, so in that case we would not need any of `nlohmann_json`, `xeus-lite`, `xeus`, `cppzmq`

Update dependencies for LFortran

---

recipes/recipes_emscripten/contourpy/build.sh
recipes/recipes_emscripten/contourpy/emscripten.meson.cross
recipes/recipes_emscripten/contourpy/recipe.yaml
recipes/recipes_emscripten/contourpy/test_contourpy.py

Update ContourPy from 1.0.7 to 1.2.0.
This is the second recipe to use `meson`, using a cross-compilation file that is very similar to NumPy's.

Update ContourPy to 1.2.0

---

empack_config.yaml

This follows advice by @martinRenou provided in 
https://github.com/jupyterlite/xeus-python-kernel/issues/79#issuecomment-1244990930
and should close 
https://github.com/jupyter-xeus/xeus-python/issues/603
(and by extension)
https://github.com/brightway-lca/brightway-live/issues/52

Add Include/Exclude Patterns for `pint` Package to `empack_config`

---

recipes/recipes_emscripten/numpy/recipe.yaml

The latest numpy we have is 1.26.0. The build for numpy 1.26.1 (#2786) doesn't work for me locally or in CI, but the trivial bumping of the tarball version in this PR works for me locally and the same goes for later 1.26.x releases, so perhaps if this works in CI we can just skip 1.26.1.

Update numpy to 1.26.2

---

recipes/recipes_emscripten/numpy/recipe.yaml

Update numpy to 1.26.3. Simple bump of version number and tarball hash.

Update numpy to 1.26.3

---

docs/development/local_builds.md
pixi.toml

Minor updates:
- Rename rattler_recipe.yaml to recipe.yaml
- Add `osx-64` platform

Update docs and platforms

---

recipes/recipes_emscripten/clarabel/build.sh
recipes/recipes_emscripten/clarabel/recipe.yaml
recipes/recipes_emscripten/clarabel/test_clarabel.py

Currently without tests integrated.
`pixi run build-emscripten-wasm32-pkg recipes/recipes_emscripten/clarabel`
returns a maturin failure where it says no python interpreter was found:
```
Running command Preparing metadata (pyproject.toml)
│ │   📦 Including license file "/Users/kerimbirgi/dev/recipes/output/bld/rattler-build_clarabel_1718116264/work/LICENSE.md"
│ │   🍹 Building a mixed python/rust project
│ │   🔗 Found pyo3 bindings with abi3 support for Python ≥ 3.7
│ │   💥 maturin failed
│ │     Caused by: $PREFIX/bin/python is not a valid python interpreter
│ │     Caused by: Failed to get information from the python interpreter at $PREFIX/bin/python
│ │     Caused by: platform.system() in python, unknown, and the rust target, Target { os: Macos, arch: X86_64, env: Unknown, triple: …
```

Add Clarabel

---

.github/workflows/build_recipes.yaml

This PR includes a rewrite of the quetz package upload action to beta.mamba.pm.
It's using `curl` instead of `quetz-client` and adds some basic HTTP status codes checks to report a successful upload and provide some basic info about what's actually gone wrong in cases like duplicate package uploads or missing permissions on beta.mamba.pm.

rewrite quetz upload action

---

recipes/recipes_emscripten/lua/CMakeLists.txt
recipes/recipes_emscripten/lua/build.sh
recipes/recipes_emscripten/lua/recipe.yaml

Added missing *.wasm file for the lua binaries (lua,luac).
It might be nice to try the Lua binary in cockle @ianthomas23

fix missing .wasm for lua binaries

---

recipes/recipes_emscripten/coreutils/build.sh
recipes/recipes_emscripten/coreutils/recipe.yaml
recipes/recipes_emscripten/grep/build.sh
recipes/recipes_emscripten/grep/recipe.yaml
recipes/recipes_emscripten/lua/CMakeLists.txt
recipes/recipes_emscripten/lua/recipe.yaml

WebAssembly modules used in [cockle](https://github.com/jupyterlite/cockle) need `TTY` exported since PR jupyterlite/cockle#23, and the lack of this is one of the causes of the CI failures in jupyterlite/cockle#25.
`cockle_fs` doesn't need it, so here adding to `coreutils` and `grep`. I'm also adding it to `lua` to help with our ongoing experiments with it.

Export TTY in WASM modules for cockle

---

recipes/recipes_emscripten/pycalphad/recipe.yaml
recipes/recipes_emscripten/pycalphad/test_pycalphad.py

This PR adds the computational thermodynamics library [`pycalphad`](https://github.com/pycalphad/pycalphad).
cc @bocklund

Add `pycalphad`

---

recipes/recipes_emscripten/cockle_fs/build.sh
recipes/recipes_emscripten/cockle_fs/recipe.yaml
recipes/recipes_emscripten/coreutils/build.sh
recipes/recipes_emscripten/coreutils/recipe.yaml
recipes/recipes_emscripten/grep/build.sh
recipes/recipes_emscripten/grep/recipe.yaml

[Cockle](https://github.com/jupyterlite/cockle) (JupyterLite terminal) now supports dynamic loading of Emscripten-built WASM modules provided the WASM is embedded in a JavaScript file. With just a few adjustments this should be able to support separate WASM and JS files. To complete that I need to build the 3 modules (`cockle_fs`, `coreutils` and `grep`) with the ~`-sMODULARIZE=1`~ `-sSINGLE_FILE=1` flag removed, which is what this PR does.
In addition, whilst we are rebuilding these recipes we can also simplify the recipes for WASM command modules (`coreutils` and `grep`) by removing the `-sINVOKE_RUN=0` flag and removing `callMain` from the list of exported runtime methods. This is because we no longer need to load the JS/WASM module in one step and then call it using `callMain` as we …

Use separate WASM and JS files for cockle

---

recipes/recipes_emscripten/libflang/build.sh
recipes/recipes_emscripten/libflang/patches/0001-Instructions-for-building-a-functional-Flang-cross-c.patch
recipes/recipes_emscripten/libflang/patches/0002-Minimal-WASM-support-for-flang.patch
recipes/recipes_emscripten/libflang/patches/0003-Specialize-Flang-to-target-WASM.patch
recipes/recipes_emscripten/libflang/patches/0004-Flang-Runtime-Explicitly-convert-shift-value-to-Subs.patch
recipes/recipes_emscripten/libflang/patches/0005-flang-IEEE_NEXT_AFTER-IEEE_NEXT_DOWN-IEEE_NEXT_UP-NE.patch
recipes/recipes_emscripten/libflang/patches/0006-Flang-Runtime-Handle-missing-definitions-in-cfenv.patch
recipes/recipes_emscripten/libflang/patches/0007-Patches-to-build-flang-runtime-with-emcc.patch
recipes/recipes_emscripten/libflang/recipe.yaml

- This only builds the `libFortranRuntime.a` required for linking Fortran libraries.
- Only the runtime patches (4-7) are strictly required, however, the others are kept for consistency with https://github.com/conda-forge/flang-feedstock/pull/69
- The package is named `libflang` also for consistency with the conda-forge feedstock

Add libflang

---

conda_build_config.yaml

This is to match the `r-base` version packaged on emscripten-forge, which is `v4.4.1`.

Update r-base version in conda_build_config

---

recipes/recipes_emscripten/r-ellipsis/recipe.yaml

Add r-ellipsis

---

recipes/recipes_emscripten/r-matrix/recipe.yaml

Add r-matrix

---

recipes/recipes_emscripten/r-base/config.site
recipes/recipes_emscripten/r-base/recipe.yaml

This fixes
```diff
- LinkError: imported function 'env.xerbla_' signature mismatch
```
when loading *libRblas.so* because
```c
// r-base/src/main/print.c
#ifdef FC_LEN_T
NORET void F77_NAME(xerbla)(const char *srname, int *info,
const FC_LEN_T srname_len)
#else
NORET void F77_NAME(xerbla)(const char *srname, int *info)
#endif
```
([source](https://github.com/wch/r-source/blob/24e4ab74c81594bdbf9e05fd60b60cff2efe4215/src/main/print.c#L1200C1-L1205C7))

Fix r-base xerbla error

---

recipes/recipes_emscripten/cockle_fs/build.sh
recipes/recipes_emscripten/cockle_fs/recipe.yaml
recipes/recipes_emscripten/coreutils/build.sh
recipes/recipes_emscripten/coreutils/recipe.yaml
recipes/recipes_emscripten/grep/build.sh
recipes/recipes_emscripten/grep/recipe.yaml
recipes/recipes_emscripten/lua/CMakeLists.txt
recipes/recipes_emscripten/lua/recipe.yaml

Update cockle packages to use emscripten 3.1.58. The packages are `cockle_fs`, `coreutils`, `grep` and `lua`. The changes comprise cherry-picking the appropriate changes from the `main` branch onto this `emscripten-3.1.58` branch and bumping the build numbers to be one larger than the previous builds.

Update cockle packages to use emscripten 3.1.58

---

recipes/recipes_emscripten/r-base64enc/recipe.yaml
recipes/recipes_emscripten/r-cli/recipe.yaml
recipes/recipes_emscripten/r-colorspace/recipe.yaml
recipes/recipes_emscripten/r-digest/recipe.yaml
recipes/recipes_emscripten/r-ellipsis/recipe.yaml
recipes/recipes_emscripten/r-fansi/recipe.yaml
recipes/recipes_emscripten/r-farver/recipe.yaml
recipes/recipes_emscripten/r-fastmap/recipe.yaml
recipes/recipes_emscripten/r-glue/recipe.yaml
recipes/recipes_emscripten/r-htmltools/recipe.yaml
recipes/recipes_emscripten/r-isoband/recipe.yaml
recipes/recipes_emscripten/r-jsonlite/recipe.yaml
recipes/recipes_emscripten/r-lattice/recipe.yaml
recipes/recipes_emscripten/r-magrittr/recipe.yaml
recipes/recipes_emscripten/r-mass/recipe.yaml
recipes/recipes_emscripten/r-matrix/recipe.yaml
recipes/recipes_emscripten/r-mgcv/recipe.yaml
recipes/recipes_emscripten/r-nlme/recipe.yaml
recipes/recipes_emscripten/r-purrr/recipe.yaml
recipes/recipes_emscripten/r-rlang/recipe.yaml
recipes/recipes_emscripten/r-tibble/recipe.yaml
recipes/recipes_emscripten/r-utf8/recipe.yaml
recipes/recipes_emscripten/r-vctrs/recipe.yaml

Since the configuration of `r-base` changed in #1374, this affects all R packages.

Rebuild R packages

---

recipes/recipes_emscripten/astropy/recipe.yaml
recipes/recipes_emscripten/astropy/test_astropy.py

Hi here!
There is a missing mandatory dependency in the recipe. I'm not sure whether it's as simple as adding it here?
This should fix https://github.com/astropy/astropy/issues/16739 and https://github.com/emscripten-forge/recipes/issues/1226

fix: astropy recipe add missing mandatory dependency

---

recipes/recipes/emscripten_emscripten-wasm32/recipe.yaml

Common entrypoints for building packages for `emscripten-forge` are:
- https://prefix.dev/blog/pixi_wasm
- https://emscripten-forge.org/development/local_builds/
In both of these, the workflow is described as:
1. Install pixi
2. `git clone https://github.com/emscripten-forge/recipes && cd recipes`
3. Initialize the environment with `pixi run setup` (referenced in the docs but not blog post).
4. Try a test build like `pixi run build-emscripten-wasm32-pkg recipes/recipes_emscripten/regex`
Right now, this fails on Macs (at least Apple Silicon?) because `rattler-build` fails to build `emscripten_emscripten-wasm32` in step 3 above (`pixi run setup`). Any subsequent build commands will also fail.
This is discussed in https://github.com/emscripten-forge/recipes/issues/1246.
The source error is …

Re-add `gettext` to `emscripten_emscripten-wasm32` recipe

---

recipes/recipes_emscripten/llvm/build.sh
recipes/recipes_emscripten/llvm/patches/lldwasm_link.patch
recipes/recipes_emscripten/llvm/recipe.yaml

Not sure why the upload to Quetz failed on all 3 previous updates on llvm 
1) https://github.com/emscripten-forge/recipes/actions/runs/11376454739/job/31648960141
2) https://github.com/emscripten-forge/recipes/actions/runs/11209653508/job/31155192548
3) https://github.com/emscripten-forge/recipes/actions/runs/11052231541/job/30703847510
Need this for CppInterOp

Fix Undefined Symbols while building llvm

---

recipes/recipes_emscripten/cairo/build.sh
recipes/recipes_emscripten/cairo/patches/cairo-wasm.patch
recipes/recipes_emscripten/cairo/recipe.yaml

Here are somethings I see
1) Building cairo locally as per the recipe on master fails
2) We need a patch that was realized by the maintainers of cairo too to compile it to emscripten (merged into master but not available in 1.18.0 so should be there till next release https://gitlab.freedesktop.org/cairo/cairo/-/issues/792)
3) I think pango expects cairo to be built with freetype and fontconfig if we want to include it as a dependency

Build Cairo with freetype

---

recipes/recipes_emscripten/llvm/patches/skip_undefined_symbols_at_link_step.patch
recipes/recipes_emscripten/llvm/recipe.yaml

Currently we see duplication of output while running xeus-cpp-lite (or rather clang-repl in the browser )

Attempt to fix output duplication through clang-repl

---

recipes/recipes_emscripten/fribidi/build.sh
recipes/recipes_emscripten/fribidi/recipe.yaml

Required to build the *cairo.so* module in `r-base`

Build fribidi with fPIC

---

recipes/recipes_emscripten/expat/build.sh
recipes/recipes_emscripten/expat/recipe.yaml

Required to build the *cairo.so* module in `r-base`.

Build expat with fPIC

---

recipes/recipes_emscripten/libpng/build.sh
recipes/recipes_emscripten/libpng/recipe.yaml

Required to build *cairo.so* module in `r-base`.

Build libpng with fPIC

---

recipes/recipes/run_modularized/recipe.yaml
recipes/recipes/run_modularized/run_modularized.js

This changes `run_modularized` to specifically look in the same directory for `*.wasm` and `*.data` files as it does for their `*.js` wrappers. This has not been a problem until now as this is the default behaviour for `*.wasm` files, but with the addition of the upcoming `vim` recipe it is not enough. `vim` ships with a set of runtime config files that are [packaged](https://emscripten.org/docs/porting/files/packaging_files.html) in a standard way in a `vim.data` file, and is loaded in a slightly different way by `vim.js` which the default behaviour doesn't cover when running in a `node` context as `run_modularized` does.
So here `locateFile` is specified when loading the wasm package so that `*.data` and `*.wasm` are correctly loaded. This is the same solution as used in `cockle`: …

Use locateFile in run_modularized

---

recipes/recipes/emscripten_emscripten-wasm32/patches/0001-Add-back-fs.findObject-and-fs.readFile-in-loadLibDat.patch
recipes/recipes/emscripten_emscripten-wasm32/patches/0001-Add-useful-error-when-symbol-resolution-fails.patch
recipes/recipes/emscripten_emscripten-wasm32/recipe.yaml

* we just use the 3.1.73 change to trigger the build of that versiob
* we revert this since we want to keep the 3.1.45 compiler on main

Revert "Emscripten 3.1.73"

---

recipes/recipes_emscripten/r-base64enc/recipe.yaml
recipes/recipes_emscripten/r-cli/recipe.yaml
recipes/recipes_emscripten/r-colorspace/recipe.yaml
recipes/recipes_emscripten/r-digest/recipe.yaml
recipes/recipes_emscripten/r-ellipsis/recipe.yaml
recipes/recipes_emscripten/r-fansi/patches/0001-Ignore-custom-limit-checks.patch
recipes/recipes_emscripten/r-fansi/recipe.yaml
recipes/recipes_emscripten/r-farver/recipe.yaml
recipes/recipes_emscripten/r-fastmap/recipe.yaml
recipes/recipes_emscripten/r-glue/recipe.yaml
recipes/recipes_emscripten/r-isoband/recipe.yaml
recipes/recipes_emscripten/r-jsonlite/recipe.yaml
recipes/recipes_emscripten/r-lattice/recipe.yaml
recipes/recipes_emscripten/r-magrittr/recipe.yaml
recipes/recipes_emscripten/r-mass/recipe.yaml
recipes/recipes_emscripten/r-nlme/recipe.yaml
recipes/recipes_emscripten/r-rlang/recipe.yaml
recipes/recipes_emscripten/r-utf8/recipe.yaml

Along with #1460, this updates the remaining R packages.
There is still an issue with incorrect flags coming from `r-base` Makeconf file, but that shall be addressed in another rebuild of all packages.

Update R packages

---

recipes/recipes_emscripten/llvm/build.sh
recipes/recipes_emscripten/llvm/patches/shift_temporary_files_to_tmp_dir.patch
recipes/recipes_emscripten/llvm/recipe.yaml

Check https://github.com/emscripten-core/emscripten/issues/23228 for detailed info

Add patch on llvm 19.1.6 to take care of temporary files generated at runtime

---

recipes/recipes/emscripten_emscripten-wasm32/recipe.yaml

fix broken emscripten-abi mutex strong-export generation. We need **strong** run exports.
The problemn is that we now have a lot of uploaded packages without the emscripten-abi.

fix broken emscripten-abi mutex strong-export generation

---

recipes/recipes_emscripten/coreutils/build.sh
recipes/recipes_emscripten/coreutils/recipe.yaml

Update `coreutils` to emscripten 3.1.73, for use in `cockle` and JupyterLite Terminal.
The addition of the new flag `-sEXIT_RUNTIME=1` is the only required change, but I have also refactored the recipe in line with other `cockle` recipes so that they will all be easier to maintain in the future.

Update coreutils to emscripten 3.1.73

---

recipes/recipes/run_modularized/recipe.yaml
recipes/recipes/run_modularized/run_modularized.js

Update `run_modularized` to emscripten 3.1.73.
This accepts exit status returned from a `main` call via `onExit` which is needed by wasm command packages built using emscripten 3.1.73 and `sEXIT_RUNTIME=1` flag. I have kept the existing codepath that accepts an exit code via the `quit` call for backward compatibility and for recipes built without the `EXIT_RUNTIME` flag.

Update run_modularized to emscripten 3.1.73

---

recipes/recipes_emscripten/lua/CMakeLists.txt
recipes/recipes_emscripten/lua/recipe.yaml

Update `lua` command package to emscripten 3.1.73. The key change is the addition of `-sEXIT_RUNTIME=1` to return an exit code. Also removed explicit declaration of `ENVIRONMENT` in line with other recipes as now using the defaullt value.
This should use the newly-built `run_modularized` to test the `onExit` callback.

Update lua to emscripten 3.1.73

---

recipes/recipes_emscripten/tree/build.sh
recipes/recipes_emscripten/tree/recipe.yaml

Update `tree` to emscripten 3.1.73. The changes all appear as additions as the previous recipe was added to the `emscripten-3.1.58` branch rather than `main`.

Update tree to emscripten 3.1.73

---

recipes/recipes_emscripten/vim/build.sh
recipes/recipes_emscripten/vim/patches/0001-const-char-args.patch
recipes/recipes_emscripten/vim/recipe.yaml

Update `vim` to emscripten 3.1.73. These are new files rather than file changes as the original recipe was added to the `3.1.58` branch not `main`.

Update vim to emscripten 3.1.73

---

recipes/recipes_emscripten/r-stringi/build.sh
recipes/recipes_emscripten/r-stringi/recipe.yaml

The environment variable `LDFLAGS=-sWASM_BIGINT` is ignored by the configure script of `r-stringi`. This causes signature mismatches when loading *stringi.so* because it is not build with `WASM_BIGINT`. Thus, it must be explicitly added.

Fix signature mismatches in r-stringi

---

recipes/recipes_emscripten/r-base/config.site
recipes/recipes_emscripten/r-base/recipe.yaml

This is to ensure downstream R packages are built with `WASM_BIGINT`

Add more WASM_BIGINT to r-base

---

recipes/recipes/cross-python_emscripten-wasm32/activate-cross-python.sh
recipes/recipes/cross-python_emscripten-wasm32/recipe.yaml

See conda-forge/cross-python-feedstock#24 and conda-forge/cross-python-feedstock#69 for relevant conda-forge issues.
Without this change, the ROS2WASM compilation fails for downstream packages of rosidl-default-generators:
```
│ ╭─ Running build script
│ │ Not activating ROS when cross-compiling
│ │ Setting up cross-python
│ │ Not activating ROS when cross-compiling
│ │ + /home/nmarticorena/Documents/pixi_project/ros-humble/recipes/ros-humble-lifecycle-msgs/build_ament_cmake.sh
│ │ USING PYTHON_EXECUTABLE=$BUILD_PREFIX/bin/python
│ │ USING PKG_CONFIG_EXECUTABLE=$BUILD_PREFIX/bin/pkg-config
│ │ Using Python 3.11
│ │ Using PYTHON_INSTALL_DIR: lib/python3.11/site-packages
│ │ configure: cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_PREFIX_PATH=$PREFIX …
```

Do not delete $PREFIX's site packages

---

recipes/recipes_emscripten/lzo/recipe.yaml

The *lzo2.pc* file is needed in other packages (cairo) to find this library.

Include pkgconfig file for lzo

---

recipes/recipes_emscripten/r-base/config.site
recipes/recipes_emscripten/r-base/pre.js
recipes/recipes_emscripten/r-base/recipe.yaml

The `--pre-js` flag gets added to the R `LDFLAGS` and this causes issues in downstream packages that depend on `r-base` because they cannot find the original `pre.js` file which only exists when building `r-base`. The file is not necessary and its contents should be overwritten depending on the use case. In `xeus-r`, this is handled by [`env_vars.js`](https://github.com/jupyter-xeus/xeus-r/blob/c3d0af4447bd3cda65b2c66ccb245b3a749d996b/wasm_patches/env_vars.js).

Remove pre.js in r-base

---

recipes/recipes_emscripten/ncurses/recipe.yaml

This is a rebuild of `ncurses` for 3.1.73 using the same version of `ncurses` in the `build` environment. Without this pin the `build` `ncurses` uses the latest 6.5 rather than the 6.4 here, and `xterminfo` has a different directory structure which eventually causes problems downstream in `vim`. Using the pin is the simplest solution here.
The only package affected by this is `vim`, for which I will submit a PR to update later today.

Rebuild ncurses against correct version

---

recipes/recipes_emscripten/vim/build.sh
recipes/recipes_emscripten/vim/recipe.yaml

Rebuild `vim` on 3.1.73 branch using updated `ncurses` and `terminfo` from PR #1931.

vim: use correct ncurses and terminfo

---

recipes/recipes/cross-r-base_emscripten-wasm32/LICENSE
recipes/recipes/cross-r-base_emscripten-wasm32/activate-cross-r-base.sh
recipes/recipes/cross-r-base_emscripten-wasm32/build.sh
recipes/recipes/cross-r-base_emscripten-wasm32/deactivate-cross-r-base.sh
recipes/recipes/cross-r-base_emscripten-wasm32/recipe.yaml

This will substitute the `cross-r-base` package from `conda-forge` used to compile R packages, and it will make it easier to build packages such as `hera` in `xeus-r`.
The downside of using `cross-r-base` from `conda-forge` is that it syncs the contents from the `BUILD_PREFIX` into `PREFIX`. This is problematic because the R packages do not get restored to their original state. With this new package, everything should remain in the `BUILD_PREFIX` and we would still be able to cross-compile R packages.

Add cross-r-base package for emscripten

---

recipes/recipes_emscripten/cockle_fs/build.sh
recipes/recipes_emscripten/cockle_fs/recipe.yaml

Create typescript definition file for `cockle_fs`. This will be used in `cockle` to correctly check types of the loaded wasm module rather than use `any` for everything.

Create typescript definition file for cockle_fs

---

recipes/recipes_emscripten/nano/build.sh
recipes/recipes_emscripten/nano/recipe.yaml

Add recipe for `nano` editor to emscripten-3.1.73 branch, for use in `cockle`. Screenshot of it in action:

Add recipe for nano to emscripten-3.1.73 branch

---

recipes/recipes_emscripten/symengine/build.sh
recipes/recipes_emscripten/symengine/patches/shared.patch
recipes/recipes_emscripten/symengine/recipe.yaml

This should help us load symengine at runtime when used with xeus-cpp-lite

Build symengine as a shared object

---

recipes/recipes_emscripten/xvega-bindings/build.sh
recipes/recipes_emscripten/xvega-bindings/recipe.yaml

Requires a rebuild of `xvega` (See https://github.com/jupyter-xeus/xvega/pull/52).

Update xvega-bindings from 0.0.10 to 0.1.0

---

recipes/recipes_emscripten/libnetcdf/build.sh
recipes/recipes_emscripten/libnetcdf/hdf5-parallel-disable.patch
recipes/recipes_emscripten/libnetcdf/parallel-disable.patch
recipes/recipes_emscripten/libnetcdf/recipe.yaml
recipes/recipes_emscripten/netcdf4/build.sh
recipes/recipes_emscripten/netcdf4/emcc_wrapper.sh
recipes/recipes_emscripten/netcdf4/py_emcc_wrapper.py
recipes/recipes_emscripten/netcdf4/recipe.yaml
recipes/recipes_emscripten/netcdf4/test_netcdf4.py
variant.yaml

third time's the charm! (see previous #1896 and #1972)
Useful for meteorological and geographical datasets. I'm personally interested in having this built as I want to use xeus python jupyterlite for my library's documentation page. 
`netcdf4` is maintained by NSF Unidata. The [python bindings in `netcdf4`](https://github.com/Unidata/netcdf4-python) depend on the [underlying C library, `libnetcdf`](https://github.com/Unidata/netcdf-c).
I am mildly conflicted about the emcc_wrapper included in netcdf4. for some reason a -R$PREFIX/bin argument was being injected and I couldn't figure out where. This "fix" is done the same way that pyproj does it (see #1170)
Thanks again @DerThorsten for your previous assistance

add netcdf4, libnetcdf

---

recipes/recipes_emscripten/xeus-cpp/recipe.yaml

Bump `xeus-cpp` build number to rebuild using latest `xeus-lite 3.1.0` that includes fixes for reading from `stdin`.

Bump xeus-cpp build number to use latest xeus-lite

---

recipes/recipes_emscripten/xeus-python/recipe.yaml

Bump `xeus-python` build number to rebuild using latest `xeus-lite 3.1.0` that includes fixes for reading from `stdin`.

Bump xeus-python build number to use latest xeus-lite

---

recipes/recipes/flang_emscripten-wasm32/activate-flang_emscripten-wasm32.sh
recipes/recipes/flang_emscripten-wasm32/recipe.yaml

This will only affect `r-base`, but the problem with the fortran library and R should be handled in `r-base` directly.

Undo replacement of fortran runtime lib in flang

---

recipes/recipes_emscripten/xeus-python/recipe.yaml

Bump `xeus-python` build number to build with latest `xeus` release that includes bug fix for `getpass` (jupyter-xeus/xeus#428).

Bump xeus-python build number to build with latest xeus release

---

docs/blog/posts/updates.md
docs/index.md
docs/project/credits.md

* Point top prefix.dev instead of the deprecated quetz instance
* Announce the changes in the posts section of the documentation

Improve documentation, add post about awesome latest changes

---

recipes/recipes_emscripten/python/build.sh
recipes/recipes_emscripten/python/recipe.yaml

- Add generic exit codes to the fake pip, wheel and python commands so that the command fails if it is invoked when building other recipes
- Rename the python version variable because it includes the major and minor version numbers

Add exit code to fake python scripts

---

recipes/recipes_emscripten/rustworkx/build.sh
recipes/recipes_emscripten/rustworkx/recipe.yaml
recipes/recipes_emscripten/rustworkx/test_rustworkx.py

Related: https://github.com/pyodide/pyodide-recipes/pull/90 and https://github.com/Qiskit/rustworkx/pull/1447
In short, this adds a very experimental rustworkx to emscripten-forge. It works with Pyodide, so I confirmed it worked with emscripten-forge as well: the tests passed after running `pixi run build-emscripten-wasm32-pkg recipes/recipes_emscripten/rustworkx`
At the current status, the other rustworkx author has not yet merged the Pyodide/emscripten-forge support. It also might take a while for us to publish 0.17.0. So I called it a pre-release with 0.17.0a3 and hosted it in my GitHub fork's release. If that is not ok, let me know.

Add `rustworkx` alpha

---

recipes/recipes_emscripten/xtensor/patches/rich_display.patch
recipes/recipes_emscripten/xtensor/recipe.yaml

Enable rich display for xtensor through xeus-cpp-lite

---

recipes/recipes_emscripten/xeus-cpp/recipe.yaml

Needed for running rich rendering and other examples with xeus-cpp-lite in notebook link.

Add nlohmann_json to xeus-cpp as runtime dependecy

---

recipes/recipes/cross-python_emscripten-wasm32/FindPython.cmake
recipes/recipes/cross-python_emscripten-wasm32/activate.sh
recipes/recipes/cross-python_emscripten-wasm32/build.sh
recipes/recipes/cross-python_emscripten-wasm32/recipe.yaml
recipes/recipes_emscripten/pyb2d3/build.sh
recipes/recipes_emscripten/pyb2d3/recipe.yaml

python extensions build with cmake, in particular extensions using nanobind rely on `FindPython.cmake` in the **build-prefix** to do the right thing. But of course it does not :/.
This ment that packages had to do horrible stuff to avoid running into issues from `FindPython.cmake`.
The following are the horrors we had to do (ie create a MyFakePythonModule and and alias from `MyFakePythonModule`to `Python::Module`):
```cmake
if(EMSCRIPTEN)
set_property(GLOBAL PROPERTY TARGET_SUPPORTS_SHARED_LIBS TRUE)
set(CMAKE_SHARED_LIBRARY_CREATE_C_FLAGS "-s SIDE_MODULE=1")
set(CMAKE_SHARED_LIBRARY_CREATE_CXX_FLAGS "-s SIDE_MODULE=1")
set(CMAKE_STRIP FALSE)  # used by default in pybind11 on .so modules
add_library(MyFakePythonModule INTERFACE)
set_target_properties(MyFakePythonModule PROPERTIES …
```

cross-python-cmake-find-python

---

recipes/recipes/cross-python_emscripten-wasm32/activate.sh
recipes/recipes/cross-python_emscripten-wasm32/recipe.yaml
recipes/recipes_emscripten/pyrsistent/build.sh
recipes/recipes_emscripten/pyrsistent/recipe.yaml
recipes/recipes_emscripten/pysocks/recipe.yaml
recipes/recipes_emscripten/pywavelets/recipe.yaml

This simplifies how python packages are built.
```bash
${PYTHON} -m pip install . ${PIP_ARGS}
```

Add default python flags to env var PIP_ARGS

---

recipes/recipes_emscripten/less/build.sh
recipes/recipes_emscripten/less/recipe.yaml

Add recipe for `less` command to run in `cockle`. It is similar to the other `cockle` command recipes that use `ncurses`.

Add recipe for `less` to run in `cockle`

---

recipes/recipes/cross-python_emscripten-wasm32/activate.sh
recipes/recipes/cross-python_emscripten-wasm32/recipe.yaml

`cmake --version` defaults to `emcmake cmake --version`

Minor fix in cross-python

---

recipes/recipes_emscripten/vim/build.sh
recipes/recipes_emscripten/vim/recipe.yaml

Disable use of `ftruncate` system call in `vim`. Fixes JupyterLite terminal issue jupyterlite/terminal#59.

`vim`: disable use of `ftruncate` system call

---

recipes/recipes_emscripten/xeus-python/recipe.yaml

Interestingly, we don't use jedi for the WASM build of xeus-python https://github.com/jupyter-xeus/xeus-python/blob/57b5416650fbfccdce9adb6747fe569961c77eb1/src/xinterpreter_wasm.cpp#L44
But it is listed as a dependency in the emscripten-forge recipe https://github.com/emscripten-forge/recipes/blob/main/recipes/recipes_emscripten/xeus-python/recipe.yaml#L34
So we should remove it from the recipe

xeus-python: Remove jedi dependency

---

emci/bot/next_version.py

Many packages do not strictly follow version updates and oftentimes skip consecutive numbering. Currently, the bot is not able to update such packages because it only checks for the next consecutive number.
```
Next versions for 4.9.4: ['4.9.5', '4.10.0', '5.0.0']
Next versions for 7.3-65: ['7.3-66', '7.4-0', '8.0-0']
Next versions for 1.5: ['1.6', '2.0']
Next versions for 4.6.0-1: ['4.6.0-2', '4.6.1-0', '4.7.0-0', '5.0.0-0']
Next versions for 1.0.0a1: ['1.0.1a1', '1.1.0a1', '2.0.0a1']
```
This PR changes the logic so that it can check for 3 consecutive version numbers in the minor and patch version numbers, to hopefully catch more package updates. This range can also be easily increased.
```
Next versions for 4.9.4: ['4.9.5', '4.9.6', '4.9.7', '4.10.0', '4.10.1', '4.10.2', '4.11.0', …
```

Iterate over a larger version range

---

recipes/recipes_emscripten/git2cpp/build.sh
recipes/recipes_emscripten/git2cpp/post.js
recipes/recipes_emscripten/git2cpp/recipe.yaml

Rebuild `git2cpp` using the latest `libgit2` that supports `git clone` in the browser.
This includes a `post.js` file containing a `Module["libgit2_convert_url"]` function that is called by `libgit2` when attempting http(s) access of a remote repository. This function is used to modify the requested URL to allow a CORS proxy to be used. The implementation here reads the environment variables `GIT_CORS_PROXY` and `GIT_CORS_PROXY_TYPE` to convert the URL, and hence the CORS proxy to be used can be set at runtime without having to rebuild `libgit2` or `git2cpp`.
As example of how to use this, for the public proxy https://corsproxy.io you would set
```
GIT_CORS_PROXY='https://corsproxy.io/?url='
```
which uses the default `GIT_CORS_PROXY_TYPE` of `prefix` to put the `GIT_CORS_PROXY` in front …

git2cpp: Update to use patched libgit2 and CORS proxy
